### ISSUE TITLE
【2024年4月2日】相关问题汇总

### ISSUE THREAD

**Issue by slience-me** [qianlima-lab/DiffShape#4]
## Environment 环境
```
python3.8
a-unet==0.0.16
einops==0.7.0
numpy==1.24.1
pandas==2.0.3
scikit-learn==1.3.2
scipy==1.10.1
sentencepiece==0.1.94
torch==2.2.2
tqdm==4.66.2
transformers==4.7.0
```

## 问题 Question: OSError: Can't load tokenizer for 't5-base'.
```If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 't5-base' is the correct path to a directory containing all relevant files for a T5Tokenizer tokenizer.```

download the relevant content link: https://huggingface.co/google-t5/t5-base/tree/main
下载相关的内容 链接 https://huggingface.co/google-t5/t5-base/tree/main

Create a folder to store the pre-trained models.
创建一个文件夹放预训练模型
![image](https://github.com/qianlima-lab/DiffShape/assets/77472835/f40e81b6-1313-4acf-9229-efeba123d644)

update the relevant content
在该文件修改
![image](https://github.com/qianlima-lab/DiffShape/assets/77472835/be75e8af-960e-4828-a163-ac4191e2fa98)
```
DEFAULT_T5_NAME = 't5-base'
DEFAULT_T5_NAME_PATH = '/自己设置的路径your own path/t5-base'
MODEL_NAME = DEFAULT_T5_NAME_PATH
```
then the train begin
然后训练开始

```
epoch : 0, train loss: 9.648278713226318, val_accu: 0.4636363636363636, stop_count: 0, test_accuracy: 0.4636363636363636
epoch : 50, train loss: 5.3995161056518555, val_accu: 0.5954545454545455, stop_count: 0, test_accuracy: 0.6742424242424242
epoch : 100, train loss: 5.188595175743103, val_accu: 0.803030303030303, stop_count: 0, test_accuracy: 0.8075757575757576
epoch : 150, train loss: 5.105463027954102, val_accu: 0.6393939393939394, stop_count: 0, test_accuracy: 0.8121212121212121
epoch : 200, train loss: 5.0810768604278564, val_accu: 0.8545454545454545, stop_count: 0, test_accuracy: 0.8303030303030303
epoch : 250, train loss: 5.074658989906311, val_accu: 0.8545454545454545, stop_count: 0, test_accuracy: 0.8303030303030303
epoch : 300, train loss: 52.27886116504669, val_accu: 0.5363636363636364, stop_count: 0, test_accuracy: 0.8303030303030303
```
but Error
但是最后报错`TypeError: forward() got an unexpected keyword argument 'x_raw_s'`

**Comment by slience-me** [comment]
您好，按照您所说的方法，我尝试着用Car数据集进行了测试，相关日志为下：
```
epoch : 0, train loss: 1.7222858667373657, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 50, train loss: 0.9501523375511169, val_accu: 0.625, stop_count: 0, test_accuracy: 0.625
epoch : 100, train loss: 0.9126665592193604, val_accu: 0.7083333333333334, stop_count: 0, test_accuracy: 0.625
epoch : 150, train loss: 0.9097163081169128, val_accu: 0.7083333333333334, stop_count: 0, test_accuracy: 0.625
epoch : 200, train loss: 0.9071618318557739, val_accu: 0.7083333333333334, stop_count: 0, test_accuracy: 0.625
epoch : 250, train loss: 0.9058945775032043, val_accu: 0.7083333333333334, stop_count: 0, test_accuracy: 0.625
epoch : 300, train loss: 4.065465807914734, val_accu: 0.25, stop_count: 0, test_accuracy: 0.625
epoch : 350, train loss: 7.995012283325195, val_accu: 0.3333333333333333, stop_count: 1, test_accuracy: 0.625
model convergent at epoch 381, early stopping
1 fold start training and evaluate
epoch : 0, train loss: 1.51633620262146, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 50, train loss: 1.1821355819702148, val_accu: 0.6666666666666666, stop_count: 0, test_accuracy: 0.7083333333333334
epoch : 100, train loss: 0.930031418800354, val_accu: 0.7916666666666666, stop_count: 0, test_accuracy: 0.6666666666666666
epoch : 150, train loss: 0.9250004291534424, val_accu: 0.7916666666666666, stop_count: 0, test_accuracy: 0.6666666666666666
epoch : 200, train loss: 0.9213310480117798, val_accu: 0.7916666666666666, stop_count: 0, test_accuracy: 0.6666666666666666
epoch : 250, train loss: 0.9236907958984375, val_accu: 0.7916666666666666, stop_count: 0, test_accuracy: 0.6666666666666666
epoch : 300, train loss: 3.1941186785697937, val_accu: 0.6666666666666666, stop_count: 0, test_accuracy: 0.6666666666666666
Traceback (most recent call last):
  File "/home/test/codehub/AssumptionAnalysis/2024-03-27-DiffShape/diffshape_ssc/main_diffshape.py", line 628, in <module>
    df_sample = df_model.sample(
  File "/home/test/codehub/AssumptionAnalysis/2024-03-27-DiffShape/diffshape_ssc/diffusion_model.py", line 210, in sample
    return self.sampler(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/codehub/AssumptionAnalysis/2024-03-27-DiffShape/diffshape_ssc/diffusion_model.py", line 179, in forward
    v_pred = self.net(x_noisy, sigmas[i], **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/a_unet/blocks.py", line 63, in forward
    return forward_fn(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/a_unet/blocks.py", line 594, in forward
    return net(x, features=features, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/codehub/AssumptionAnalysis/2024-03-27-DiffShape/diffshape_ssc/blocks.py", line 63, in forward
    return forward_fn(*args, **kwargs)
  File "/home/test/codehub/AssumptionAnalysis/2024-03-27-DiffShape/diffshape_ssc/blocks.py", line 551, in forward
    return net(x, embedding=embedding, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/a_unet/apex.py", line 431, in forward
    return self.net(x, features, embedding, channels)  # type: ignore
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/a_unet/apex.py", line 382, in forward
    x = self.block(x, features, embedding, channels)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/a_unet/blocks.py", line 77, in forward
    x = block(x, *args)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/a_unet/blocks.py", line 103, in forward
    x, ps = pack([x], "b d *")
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/einops/packing.py", line 85, in pack
    backend.reshape(tensor, (*shape[:n_axes_before], -1, *shape[axis_after_packed_axes:]))
  File "/home/test/anaconda3/envs/diffshape_ssc/lib/python3.8/site-packages/einops/_backends.py", line 92, in reshape
    return x.reshape(shape)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 8, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```
针对这个错误，尝试着更改

**Comment by Guuuli** [comment]
我很奇怪，我只是解决了一些报错，为什么运行的日志与你们的日志相差较大。日志如下，请指教：
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Start training on Car
0 fold start training and evaluate
/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/main_diffshape.py:421: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:178.)
  val_set = UCRDataset(torch.from_numpy(val_dataset).to(device),
/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/conv.py:303: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at  ../aten/src/ATen/native/Convolution.cpp:883.)
  return F.conv1d(input, weight, bias, self.stride,
epoch : 0, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 50, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 100, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 150, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 200, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 250, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 300, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
Traceback (most recent call last):
  File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/main_diffshape.py", line 612, in <module>
    df_sample = df_model.sample(noise, num_steps=10,
  File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/diffusion_model.py", line 208, in sample
    return self.sampler(*args, **kwargs)
  File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/diffusion_model.py", line 177, in forward
    v_pred = self.net(x_noisy, sigmas[i], **kwargs)
  File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/a_unet/blocks.py", line 63, in forward
    return forward_fn(*args, **kwargs)
  File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/a_unet/blocks.py", line 594, in forward
    return net(x, features=features, **kwargs)
  File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/blocks.py", line 63, in forward
    return forward_fn(*args, **kwargs)
  File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/blocks.py", line 551, in forward
    return net(x, embedding=embedding, **kwargs)
  File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'x_raw_s'

**Comment by Guuuli** [comment]
我很奇怪，我只是解决了一些报错，为什么运行的日志与你们的日志相差较大。其中train loss为nan，并且accuracy不发生改变。日志如下，请指教：
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the legacy (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set legacy=False. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Start training on Car
0 fold start training and evaluate
/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/main_diffshape.py:421: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:178.)
val_set = UCRDataset(torch.from_numpy(val_dataset).to(device),
/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/conv.py:303: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at ../aten/src/ATen/native/Convolution.cpp:883.)
return F.conv1d(input, weight, bias, self.stride,
epoch : 0, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 50, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 100, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 150, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 200, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 250, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
epoch : 300, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25
Traceback (most recent call last):
File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/main_diffshape.py", line 612, in
df_sample = df_model.sample(noise, num_steps=10,
File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/diffusion_model.py", line 208, in sample
return self.sampler(*args, **kwargs)
File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/diffusion_model.py", line 177, in forward
v_pred = self.net(x_noisy, sigmas[i], **kwargs)
File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/a_unet/blocks.py", line 63, in forward
return forward_fn(*args, **kwargs)
File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/a_unet/blocks.py", line 594, in forward
return net(x, features=features, **kwargs)
File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/blocks.py", line 63, in forward
return forward_fn(*args, **kwargs)
File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/blocks.py", line 551, in forward
return net(x, embedding=embedding, **kwargs)
File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'x_raw_s'

**Comment by beijixing12** [comment]
你好，作者发表在24ICDE上的文章When Multi-Behavior Meets Multi-Interest:
 Multi-Behavior Sequential Recommendation with
 Multi-Interest Self-Supervised Learning
 的开源代码网址https://github.com/qianlima-lab/MISSL报错404，请问能否上传一下？

**Comment by beijixing12** [comment]
你好，作者发表在24ICDE上的文章When Multi-Behavior Meets Multi-Interest:
Multi-Behavior Sequential Recommendation with
Multi-Interest Self-Supervised Learning
的开源代码网址[https://github.com/qianlima-lab/MISSL
报错404，请问能否上传一下？

**Comment by ZLiu21** [comment]
> https://github.com/qianlima-lab/MISSL

当前这篇24 ICDE的github链接能够正常访问

**Comment by ZLiu21** [comment]
> 我很奇怪，我只是解决了一些报错，为什么运行的日志与你们的日志相差较大。其中train loss为nan，并且accuracy不发生改变。日志如下，请指教： You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the legacy (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set legacy=False. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in [huggingface/transformers#24565](https://github.com/huggingface/transformers/pull/24565) Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Start training on Car 0 fold start training and evaluate /mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/main_diffshape.py:421: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:178.) val_set = UCRDataset(torch.from_numpy(val_dataset).to(device), /home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/conv.py:303: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at ../aten/src/ATen/native/Convolution.cpp:883.) return F.conv1d(input, weight, bias, self.stride, epoch : 0, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25 epoch : 50, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25 epoch : 100, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25 epoch : 150, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25 epoch : 200, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25 epoch : 250, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25 epoch : 300, train loss: nan, val_accu: 0.25, stop_count: 0, test_accuracy: 0.25 Traceback (most recent call last): File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/main_diffshape.py", line 612, in df_sample = df_model.sample(noise, num_steps=10, File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/diffusion_model.py", line 208, in sample return self.sampler(*args, **kwargs) File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/diffusion_model.py", line 177, in forward v_pred = self.net(x_noisy, sigmas[i], **kwargs) File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/a_unet/blocks.py", line 63, in forward return forward_fn(*args, **kwargs) File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/a_unet/blocks.py", line 594, in forward return net(x, features=features, **kwargs) File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/blocks.py", line 63, in forward return forward_fn(*args, **kwargs) File "/mnt/mydisk2/gyl/DiffShape/experiment/diffshape_ssc/diffusion/blocks.py", line 551, in forward return net(x, embedding=embedding, **kwargs) File "/home/omnisky/.conda/envs/guIR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) TypeError: forward() got an unexpected keyword argument 'x_raw_s'

上面报错可能是由于包版本依赖不正确导致，请试试python 3.7，torch 1.1环境。如果还遇到报错，欢迎给出具体的数据集名称，我这边可以协助调试分析看看

**Comment by ZLiu21** [comment]
> 你好，这个错误我根据代码的意思理解就是：他在通过扩散模型生成仿真的shapelet时，只用到了有标签的数据，而你在运行时估计有一个batchsize没有有标签数据在里面，导致这个错误，你应该还得加一个判断，如果当前batchsize都是没标签数据应该不进行扩散模型生成，这点也是我当时读论文和代码产生的一点疑问，好像文中没说，文章中的意思应该是全部都进行扩散模型再生成一个仿真的shapelet，但是它给的代码只让有标签数据进行扩散模型。如有理解错误还望纠正。

你的理解是对的，扩散生成过程只生成有标注和高质量伪标注样本的shapelet，而不会去生成置信度地伪标注样本的shapelet，这样能够大大降低生成过程的耗时
